# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('diagnosis', models.CharField(max_length=160)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('milk_withdrawal_until', models.DateTimeField(blank=True, null=True)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='herd.herdgroup')),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.input')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=160)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_withdrawals', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_withdrawals', to='herd.farm')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='health.treatment')),
            ],
            options={
                'ordering': ['-ends_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['started_at'], name='health_trea_started_5bd352_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['milk_withdrawal_until'], name='health_trea_milk_wi_b6697b_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['source_event_id'], name='health_trea_source__0fc9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='milkwithdrawal',
            index=models.Index(fields=['ends_at'], name='health_milk_ends_at_cba82b_idx'),
        ),
        migrations.AddIndex(
            model_name='milkwithdrawal',
            index=models.Index(fields=['source_event_id'], name='health_milk_source__684167_idx'),
        ),
    ]
