# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMovementGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=160)),
                ('transporter_ruc', models.CharField(blank=True, max_length=13)),
                ('transporter_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('submitted', 'Enviada'), ('authorized', 'Autorizada'), ('rejected', 'Rechazada')], default='draft', max_length=20)),
                ('access_key', models.CharField(blank=True, db_index=True, max_length=49)),
                ('authorization_number', models.CharField(blank=True, max_length=80)),
                ('authorization_date', models.DateTimeField(blank=True, null=True)),
                ('sri_response', models.JSONField(blank=True, default=dict)),
                ('animals', models.ManyToManyField(blank=True, related_name='movement_guides', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_guides', to='herd.farm')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['issue_date'], name='billing_ani_issue_d_408767_idx'), models.Index(fields=['status'], name='billing_ani_status_4309a1_idx'), models.Index(fields=['access_key'], name='billing_ani_access__f8bf0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilkInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('buyer_ruc', models.CharField(max_length=13)),
                ('buyer_name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('liters', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('submitted', 'Enviada'), ('authorized', 'Autorizada'), ('rejected', 'Rechazada')], default='draft', max_length=20)),
                ('access_key', models.CharField(blank=True, db_index=True, max_length=49)),
                ('authorization_number', models.CharField(blank=True, max_length=80)),
                ('authorization_date', models.DateTimeField(blank=True, null=True)),
                ('sri_response', models.JSONField(blank=True, default=dict)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_invoices', to='herd.farm')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['issue_date'], name='billing_mil_issue_d_401593_idx'), models.Index(fields=['status'], name='billing_mil_status_26d80d_idx'), models.Index(fields=['access_key'], name='billing_mil_access__371751_idx')],
            },
        ),
    ]
