# Generated by Django 6.1 on 2026-09-30 14:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymovement_movement_type'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-ordered_on', '-created_at'], 'permissions': [('submit_purchaseorder', 'Puede enviar ordenes para aprobacion'), ('approve_purchaseorder', 'Puede aprobar o rechazar ordenes'), ('receive_purchaseorder', 'Puede recibir ordenes en bodega'), ('manage_purchaseinvoice', 'Puede registrar facturas de compra'), ('pay_purchaseinvoice', 'Puede registrar pagos a proveedores'), ('return_purchase', 'Puede devolver compras al proveedor')]},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de aprobacion'), ('ordered', 'Ordenada'), ('partial', 'Recibida parcialmente'), ('received', 'Recibida'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Pago parcial'), ('paid', 'Pagada'), ('cancelled', 'Anulada')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='procurement.purchaseorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_on', 'issued_on'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia'), ('card', 'Tarjeta'), ('other', 'Otro')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.purchaseinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reason', models.CharField(max_length=255)),
                ('credit_document', models.CharField(blank=True, max_length=80)),
                ('inventory_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return', to='inventory.inventorymovement')),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='procurement.goodsreceiptline')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='nonnegative_purchase_invoice_total'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0), ('credit_amount__lte', models.F('total_amount'))), name='valid_purchase_invoice_credit'),
        ),
        migrations.AddConstraint(
            model_name='purchasepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_purchase_payment'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_purchase_return_quantity'),
        ),
    ]
