# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('cost_type', models.CharField(choices=[('feed', 'Balanceado'), ('medicine', 'Medicina'), ('vaccine', 'Vacuna'), ('semen', 'Semen'), ('supplement', 'Suplemento'), ('supply', 'Insumo'), ('other', 'Otro')], max_length=30)),
                ('cost_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('inventory_movement_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_allocations', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocations', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_allocations', to='herd.herdgroup')),
            ],
            options={
                'ordering': ['-cost_date', '-created_at'],
                'indexes': [models.Index(fields=['cost_date'], name='finance_cos_cost_da_14ee6d_idx'), models.Index(fields=['source_event_id'], name='finance_cos_source__f396c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('revenue_type', models.CharField(choices=[('milk', 'Leche'), ('animal_sale', 'Venta animal'), ('other', 'Otro')], max_length=30)),
                ('revenue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_entries', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries', to='herd.herdgroup')),
            ],
            options={
                'ordering': ['-revenue_date', '-created_at'],
                'indexes': [models.Index(fields=['revenue_date'], name='finance_rev_revenue_1cb4e2_idx'), models.Index(fields=['source_event_id'], name='finance_rev_source__db8b8c_idx')],
            },
        ),
    ]
