# Generated by Django 6.1 on 2026-08-28 22:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costallocation',
            name='cost_type',
            field=models.CharField(choices=[('feed', 'Balanceado'), ('medicine', 'Medicina'), ('vaccine', 'Vacuna'), ('semen', 'Semen'), ('supplement', 'Suplemento'), ('supply', 'Insumo'), ('labor', 'Mano de obra'), ('service', 'Servicios'), ('shrinkage', 'Merma'), ('other', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='OperatingPeriodSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('farm', 'Hacienda'), ('group', 'Lote'), ('animal', 'Animal'), ('unassigned', 'Sin asignar')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('saleable_liters', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('discarded_liters', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('discarded_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('costs', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('net_profit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('cost_per_liter', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('cost_per_saleable_liter', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('margin_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pnl_snapshots', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pnl_snapshots', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pnl_snapshots', to='herd.herdgroup')),
            ],
            options={
                'ordering': ['-end_date', 'scope', 'farm__name'],
                'indexes': [models.Index(fields=['farm', 'start_date', 'end_date'], name='finance_ope_farm_id_e8b018_idx'), models.Index(fields=['scope', 'end_date'], name='finance_ope_scope_6afaa2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='valid_operating_snapshot_window'), models.UniqueConstraint(condition=models.Q(('scope', 'farm')), fields=('farm', 'start_date', 'end_date'), name='unique_farm_period_snapshot'), models.UniqueConstraint(condition=models.Q(('group__isnull', False), ('scope', 'group')), fields=('farm', 'group', 'start_date', 'end_date'), name='unique_group_period_snapshot'), models.UniqueConstraint(condition=models.Q(('animal__isnull', False), ('scope', 'animal')), fields=('farm', 'animal', 'start_date', 'end_date'), name='unique_animal_period_snapshot'), models.UniqueConstraint(condition=models.Q(('scope', 'unassigned')), fields=('farm', 'start_date', 'end_date'), name='unique_unassigned_period_snapshot')],
            },
        ),
    ]
