# Generated by Django 6.1 on 2026-09-29 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil de empresa',
                'verbose_name_plural': 'perfiles de empresa',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('foundation', 'Plataforma'), ('operations', 'Operaciones'), ('production', 'Produccion'), ('inventory', 'Inventario'), ('finance', 'Finanzas'), ('compliance', 'Cumplimiento'), ('analytics', 'Analitica')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='required_by', to='configuration.capabilitydefinition')),
                ('compatible_profiles', models.ManyToManyField(blank=True, related_name='capabilities', to='configuration.profiledefinition')),
            ],
            options={
                'verbose_name': 'capacidad',
                'verbose_name_plural': 'capacidades',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Prueba'), ('enabled', 'Habilitada'), ('suspended', 'Suspendida')], default='enabled', max_length=20)),
                ('enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='configuration.capabilitydefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_assignments', to='tenants.client')),
            ],
            options={
                'ordering': ['organization__name', 'capability__category', 'capability__name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'capability'), name='unique_capability_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='tenants.client')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='configuration.profiledefinition')),
            ],
            options={
                'ordering': ['organization__name', 'profile__sort_order', 'profile__name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'profile'), name='unique_profile_per_organization')],
            },
        ),
    ]
