# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('milking_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('morning', 'Manana'), ('afternoon', 'Tarde'), ('night', 'Noche'), ('total_day', 'Total dia')], default='total_day', max_length=20)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milking_sessions', to='herd.farm')),
            ],
            options={
                'ordering': ['-milking_date', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='MilkYield',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=10)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_yields', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_yields', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_yields', to='herd.herdgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='milk.milkingsession')),
            ],
            options={
                'ordering': ['-session__milking_date', 'animal__tag'],
            },
        ),
        migrations.AddIndex(
            model_name='milkingsession',
            index=models.Index(fields=['milking_date'], name='milk_milkin_milking_a5b481_idx'),
        ),
        migrations.AddIndex(
            model_name='milkingsession',
            index=models.Index(fields=['source_event_id'], name='milk_milkin_source__ebc48f_idx'),
        ),
    ]
