# Generated by Django 6.1 on 2026-08-28 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0001_initial'),
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkyield',
            name='discard_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='milkyield',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkyield',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='milkyield',
            index=models.Index(fields=['is_discarded'], name='milk_milkyi_is_disc_f7408a_idx'),
        ),
    ]
