# Generated by Django 6.1 on 2026-09-30 13:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('trade_name', models.CharField(blank=True, max_length=180)),
                ('identification_type', models.CharField(choices=[('ruc', 'RUC'), ('cedula', 'Cedula'), ('passport', 'Pasaporte'), ('other', 'Otro')], default='ruc', max_length=20)),
                ('identification_number', models.CharField(blank=True, max_length=30)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_producer', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_carrier', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'contraparte',
                'verbose_name_plural': 'contrapartes',
                'ordering': ['legal_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('identification_number', ''), _negated=True), fields=('identification_number',), name='unique_counterparty_identification'), models.CheckConstraint(condition=models.Q(('is_supplier', True), ('is_producer', True), ('is_customer', True), ('is_carrier', True), _connector='OR'), name='counterparty_has_role')],
            },
        ),
    ]
