# Generated by Django 6.1 on 2026-09-29 20:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import decimal
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('forage_type', models.CharField(blank=True, max_length=120)),
                ('rest_target_days', models.PositiveSmallIntegerField(default=21, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_animals', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paddocks', to='herd.farm')),
            ],
            options={
                'ordering': ['farm__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrazingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('planned_end_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('head_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('entry_biomass_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('exit_biomass_kg_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grazing_periods', to='herd.farm')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grazing_periods', to='herd.herdgroup')),
                ('paddock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grazing_periods', to='grazing.paddock')),
            ],
            options={
                'ordering': ['-started_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paddock',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_paddock_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='paddock',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='unique_paddock_code_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='paddock',
            constraint=models.CheckConstraint(condition=models.Q(('area_hectares__gt', 0)), name='positive_paddock_area'),
        ),
        migrations.AddConstraint(
            model_name='paddock',
            constraint=models.CheckConstraint(condition=models.Q(('rest_target_days__gt', 0)), name='positive_paddock_rest_target'),
        ),
        migrations.AddIndex(
            model_name='grazingperiod',
            index=models.Index(fields=['farm', 'started_on'], name='grazing_gra_farm_id_92f275_idx'),
        ),
        migrations.AddIndex(
            model_name='grazingperiod',
            index=models.Index(fields=['paddock', 'started_on'], name='grazing_gra_paddock_881273_idx'),
        ),
        migrations.AddIndex(
            model_name='grazingperiod',
            index=models.Index(fields=['group', 'started_on'], name='grazing_gra_group_i_f69e94_idx'),
        ),
        migrations.AddIndex(
            model_name='grazingperiod',
            index=models.Index(fields=['source_event_id'], name='grazing_gra_source__a43f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='grazingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('paddock',), name='one_active_period_per_paddock'),
        ),
        migrations.AddConstraint(
            model_name='grazingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('group',), name='one_active_period_per_group'),
        ),
        migrations.AddConstraint(
            model_name='grazingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='grazing_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='grazingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end_on__isnull', True), ('planned_end_on__gte', models.F('started_on')), _connector='OR'), name='grazing_planned_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='grazingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('head_count__gt', 0)), name='positive_grazing_head_count'),
        ),
    ]
