# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('feed', 'Balanceado'), ('medicine', 'Medicina'), ('vaccine', 'Vacuna'), ('semen', 'Semen'), ('supplement', 'Suplemento'), ('supply', 'Insumo')], max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('sack', 'Saco'), ('dose', 'Dosis'), ('ml', 'Ml'), ('unit', 'Unidad')], max_length=20)),
                ('default_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('milk_withdrawal_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='unique_input_sku')],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('lot_code', models.CharField(blank=True, max_length=80)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='herd.farm')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='inventory.input')),
            ],
            options={
                'ordering': ['input__name', 'expires_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Consumo'), ('adjustment', 'Ajuste')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='herd.herdgroup')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.input')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocklot')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='inventory_i_occurre_ddb254_idx'), models.Index(fields=['source_event_id'], name='inventory_i_source__ff7edc_idx')],
            },
        ),
    ]
