# Generated by Django 6.1 on 2026-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
