# Generated by Django 6.1 on 2026-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocklot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Ingreso'), ('out', 'Consumo'), ('adjustment', 'Ajuste'), ('return', 'Devolucion a proveedor')], max_length=20),
        ),
    ]
