# Generated by Django 6.1 on 2026-09-29 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_alter_costallocation_cost_type_and_more'),
        ('grazing', '0001_initial'),
        ('herd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=160)),
                ('position', models.CharField(choices=[('foreman', 'Mayordomo'), ('livestock', 'Ganaderia'), ('milking', 'Ordeno'), ('agriculture', 'Campo y cultivo'), ('technician', 'Tecnico'), ('administration', 'Administracion'), ('other', 'Otro')], default='other', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hired_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='herd.farm')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['farm__name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('livestock', 'Hato'), ('milking', 'Ordeno'), ('health', 'Sanidad'), ('reproduction', 'Reproduccion'), ('grazing', 'Pastoreo'), ('inventory', 'Bodega'), ('maintenance', 'Mantenimiento'), ('other', 'Otro')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('scheduled_for', models.DateField(default=django.utils.timezone.localdate)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('instructions', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='herd.animal')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workforce.worker')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='herd.herdgroup')),
                ('paddock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='grazing.paddock')),
            ],
            options={
                'ordering': ['scheduled_for', '-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('labor_cost', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('cost_allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_log', to='finance.costallocation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='workforce.worker')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to='workforce.worktask')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='unique_worker_code_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='nonnegative_worker_hourly_rate'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('hired_on')), _connector='OR'), name='worker_end_after_hire'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['farm', 'scheduled_for', 'status'], name='workforce_w_farm_id_47b89e_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['assigned_to', 'scheduled_for', 'status'], name='workforce_w_assigne_fbe20c_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['worker', 'work_date'], name='workforce_w_worker__2eb686_idx'),
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_id__isnull', False)), fields=('source_event_id',), name='unique_work_log_source_event'),
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='positive_work_log_hours'),
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.CheckConstraint(condition=models.Q(('labor_cost__gte', 0)), name='nonnegative_work_log_cost'),
        ),
    ]
