# Generated by Django 6.1 on 2026-08-28 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEvent',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('device_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_sequence', models.PositiveBigIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido'), ('conflict', 'Conflicto')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['client_sequence', 'created_at'],
                'indexes': [models.Index(fields=['device_id', 'client_sequence'], name='sync_incomi_device__59464a_idx'), models.Index(fields=['event_type', 'occurred_at'], name='sync_incomi_event_t_f66139_idx'), models.Index(fields=['status'], name='sync_incomi_status_2f31ea_idx')],
            },
        ),
    ]
