# Generated by Django 6.1 on 2026-09-30 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Creacion'), ('update', 'Actualizacion'), ('delete', 'Eliminacion')], max_length=20)),
                ('model_label', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(db_index=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(default=dict)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('request_method', models.CharField(blank=True, max_length=12)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('export_audit', 'Puede exportar la auditoria')],
                'indexes': [models.Index(fields=['model_label', 'object_id', 'created_at'], name='audit_audit_model_l_35ec75_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx')],
            },
        ),
    ]
