# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('heat', 'Celo'), ('service', 'Inseminacion/Monta'), ('pregnancy_check', 'Chequeo prenez'), ('calving', 'Parto'), ('dry_off', 'Secado')], max_length=30)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('service_type', models.CharField(blank=True, choices=[('ai', 'Inseminacion artificial'), ('natural', 'Monta natural')], max_length=20)),
                ('sire_identifier', models.CharField(blank=True, max_length=80)),
                ('pregnancy_positive', models.BooleanField(blank=True, null=True)),
                ('calf_tag', models.CharField(blank=True, max_length=40)),
                ('calf_sex', models.CharField(blank=True, max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reproduction_events', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reproduction_events', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction_events', to='herd.herdgroup')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_on'], name='reproductio_event_t_4ebe4d_idx'), models.Index(fields=['source_event_id'], name='reproductio_source__d761bd_idx')],
            },
        ),
    ]
