# Generated by Django 6.1 on 2026-09-29 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('weighed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('scale_identifier', models.CharField(blank=True, max_length=120)),
                ('source_event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_records', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_records', to='herd.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_records', to='herd.herdgroup')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weighed_on', '-created_at'],
                'indexes': [models.Index(fields=['animal', 'weighed_on'], name='growth_weig_animal__82e87a_idx'), models.Index(fields=['group', 'weighed_on'], name='growth_weig_group_i_9e0d1d_idx'), models.Index(fields=['source_event_id'], name='growth_weig_source__04ff98_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='positive_weight_record_kg'), models.CheckConstraint(condition=models.Q(('body_condition_score__isnull', True), models.Q(('body_condition_score__gte', 1), ('body_condition_score__lte', 5)), _connector='OR'), name='valid_weight_body_condition_score')],
            },
        ),
    ]
