# Generated by Django 6.1 on 2026-08-28 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('canton', models.CharField(blank=True, max_length=80)),
                ('parish', models.CharField(blank=True, max_length=80)),
                ('default_milk_price', models.DecimalField(decimal_places=4, default=Decimal('0.45'), max_digits=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HerdGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('group_type', models.CharField(choices=[('lot', 'Lote'), ('paddock', 'Potrero'), ('management', 'Manejo')], default='lot', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='herd.farm')),
            ],
            options={
                'ordering': ['farm__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('female', 'Hembra'), ('male', 'Macho')], default='female', max_length=10)),
                ('status', models.CharField(choices=[('calf', 'Ternera'), ('heifer', 'Vientre'), ('lactating', 'En lactancia'), ('dry', 'Seca'), ('pregnant', 'Prenada'), ('sold', 'Vendida'), ('dead', 'Muerta'), ('culled', 'Descartada')], default='heifer', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('bos_taurus_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bos_indicus_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lactation_number', models.PositiveSmallIntegerField(default=0)),
                ('last_calving_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('confirmed_pregnant_at', models.DateField(blank=True, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('dry_off_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='herd.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='herd.farm')),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='herd.herdgroup')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddConstraint(
            model_name='herdgroup',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_group_name_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'tag'), name='unique_animal_tag_per_farm'),
        ),
    ]
